name: yahaal_test
description: A.
publish_to: 'none' 





version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  logger: ^1.4.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter





  build_runner: ^2.3.3





  flutter_lints: ^2.0.0
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  fluttertoast: ^8.1.2
  mockito: ^5.3.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_html: ^3.0.0-alpha.5






flutter:




  uses-material-design: true


  assets:
     - assets/


  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
